# Generated by Django 2.2 on 2019-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_crossword', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bestTime',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
