# Generated by Django 2.2 on 2019-04-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_crossword', '0003_auto_20190427_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bestTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(),
        ),
    ]
