# Generated by Django 2.2 on 2019-04-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_crossword', '0004_auto_20190427_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bestTime',
        ),
    ]
