# Generated by Django 2.2 on 2019-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_crossword', '0006_auto_20190427_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bestTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
