# Generated by Django 2.2 on 2019-04-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_crossword', '0008_statistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
