# Generated by Django 2.2 on 2019-05-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_crossword', '0011_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
    ]
